<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jazz-PC" ignored="0" name="Test02" tests="2" failures="1" timestamp="2022-02-27T19:44:22 IST" time="40.011" errors="0">
  <testcase name="loginmethod" time="5.475" classname="testCases.AddToCartTC01">
    <failure type="java.lang.AssertionError" message="Test case failed, user not logged in expected [https://www.flipkart.com/] but found [https://www.flipkart.com/account/login]">
      <![CDATA[java.lang.AssertionError: Test case failed, user not logged in expected [https://www.flipkart.com/] but found [https://www.flipkart.com/account/login]
at testCases.AddToCartTC01.loginmethod(AddToCartTC01.java:54)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginmethod -->
  <testcase name="SearchAndAddToCart" time="0.0" classname="testCases.AddToCartTC01">
    <skipped/>
  </testcase> <!-- SearchAndAddToCart -->
</testsuite> <!-- Test02 -->
